packages:
- .
extra-deps:
- newtype-generics-0.4
# - Stream-0.4.7.2
# - applicative-numbers-0.1.3
# - lazysmallcheck-0.6
# - vector-space-0.10.4
# - MemoTrie-0.6.5
# - marked-pretty-1.1.2.1
resolver: nightly-2016-07-18
flags: {}
