flags: {}
# resolver: lts-7.15
# resolver: nightly-2017-01-17
# compiler: ghc-8.0.2
# system-ghc: true
resolver: nightly-2017-01-25

# These extras are to help with ghc-8.0.2, but I still get "This package
# indirectly depends on multiple versions of the same". Oddly, I don't see any
# conflicts in the list.

# extra-deps:
# - newtype-generics-0.4
# - directory-1.3.0.0
# - filepath-1.4.1.1
# - process-1.4.3.0
# - unix-2.7.2.1

