flags: {}
packages:
- classes
- plugin
- examples
- graphics
- hardware
- location:
    git: https://github.com/ku-fpg/netlist
    commit: c58d089f0349e9a3e9f9e264c7108c3d0b4ea4fd
  subdirs:
  - netlist
  - verilog
  - netlist-to-verilog
  extra-dep: true
extra-deps:
- mersenne-random-1.0.0.1
- newtype-generics-0.5.0.1
- vector-random-0.1
resolver: lts-9.3
