flags: {}
packages:
- inline
- satisfy
- classes
- plugin
- examples
- graphics
- hardware
- sandbox
- location:
    git: https://github.com/ku-fpg/netlist
    commit: c58d089f0349e9a3e9f9e264c7108c3d0b4ea4fd
  subdirs:
  - netlist
  - verilog
  - netlist-to-verilog
  extra-dep: true
# While waiting for https://hackage.haskell.org/package/vector-sized post 0.6.1.0.
# Then update the vector-sized lower bound in *.cabal
- location:
    git: https://github.com/expipiplus1/vector-sized
    commit: 2e5ebd857af957fa5709f5ad17df1b5851664b70
  extra-dep: true
extra-deps:
  - pointed-5.0.1 ## instances for GHC.Generics
  - keys-3.12     ## instances for GHC.Generics
  - ghc-typelits-natnormalise-0.5.8
resolver: lts-9.20
