packages:
- '.'
- ../MemoTrie
- ../vector-space
- location:
    git: https://github.com/ekmett/keys
    commit: 614bba8a4676bc8d5c8cc0ae94bef614ccfae71f
  extra-dep: true
extra-deps:
- newtype-generics-0.4
- Stream-0.4.7.2
# - TypeCompose-0.9.12
- applicative-numbers-0.1.3
# - keys-3.12
- lazysmallcheck-0.6
# - ty-0.1.7

resolver: nightly-2016-07-18
flags: {}
