flags: {}
packages:
- inline
- known
- satisfy
- classes
- plugin
- examples
- graphics
- hardware
- sandbox
- location:
    git: https://github.com/ku-fpg/netlist
    commit: 8f7cb58ea966c8faefdffe99c53258cd1e3a1221
  subdirs:
  - netlist
  - verilog
  - netlist-to-verilog
  extra-dep: true
extra-deps:
  # The next three provide instances for GHC.Generics
  - pointed-5.0.1
  - keys-3.12
  - adjunctions-4.4
  - z3-4.3.1         ## For the SMT category
  - vector-sized-1.0.0.0
  - indexed-list-literals-0.1.0.1
  # The next three are for ConCat.Finite
  - ghc-typelits-knownnat-0.5
  - ghc-typelits-natnormalise-0.6.1
  - ghc-tcplugins-extra-0.3
  - newtype-generics-0.5.3
  - language-glsl-0.2.1

# resolver: lts-9.20 # ghc-8.0.2
resolver: lts-11.12 # ghc-8.2.2
# resolver: lts-12.4 # ghc-8.4.3

